### ISSUE TITLE
upload_pcap.py issue

### ISSUE THREAD

**Issue by marwanabdelhadi** [riverbed/steelscript-appresponse#3]
when i execute this script always give me string index out of range error. any thoughts how i can solve this issue?

C:\Python27\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Uploading http.pcap
Traceback (most recent call last):
  File "upload_pcap.py", line 51, in <module>
    app.run()
  File "C:\Python27\lib\site-packages\steelscript\common\app.py", line 35, in run
    self.parse(sys.argv[1:])
  File "C:\Python27\lib\site-packages\steelscript\commands\steel.py", line 306, in parse
    self.main()
  File "upload_pcap.py", line 41, in main
    local_file=self.options.filepath
  File "C:\Python27\lib\site-packages\steelscript\appresponse\core\appresponse.py", line 256, in upload
    if dest_dir[0] == '/':
IndexError: string index out of range

**Comment by marwanabdelhadi** [comment]
I run the script to upload pcap file to ARX11.6 physical appliance

**Comment by mgarabed** [comment]
Can you provide the arguments for how you are calling the script?  There seems to be an issue with the format of the destination file name.

**Comment by marwanabdelhadi** [comment]
Hello Mike,

Sorry for not back to you in this issue, actually i didn't mentioned any --destname as i expected that script will using the default name, however I mentioned a --destname now in the script running but give me the following error:

PS C:\Users\abdelhm\Desktop> python upload_pcap.py x.x.x.x -u admin -p xxxxxx --filepath file2.pcapng --destname /admin/http.pcap
C:\Python27\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Uploading file2.pcapng
C:\Python27\lib\site-packages\requests\utils.py:133: FileModeWarning: Requests has determined the content-length for this request using the binary size of the file: however, the file has been opened in text mode (i.e. without the 'b' flag in the mode). This may lead to an incorrect content-length. In Requests 3.0, support will be removed for files in text mode.
  FileModeWarning
Traceback (most recent call last):
  File "upload_pcap.py", line 51, in <module>
    app.run()
  File "C:\Python27\lib\site-packages\steelscript\common\app.py", line 35, in run
    self.parse(sys.argv[1:])
  File "C:\Python27\lib\site-packages\steelscript\commands\steel.py", line 306, in parse
    self.main()
  File "upload_pcap.py", line 41, in main
    local_file=self.options.filepath
  File "C:\Python27\lib\site-packages\steelscript\appresponse\core\appresponse.py", line 266, in upload
    resp = conn.upload(uri, f, extra_headers=headers)
  File "C:\Python27\lib\site-packages\steelscript\common\connection.py", line 524, in upload
   extra_headers=extra_headers)
  File "C:\Python27\lib\site-packages\steelscript\common\connection.py", line 297, in _request
    raise exc
steelscript.common.exceptions.RvbdHTTPException: 502 Upstream server is not ready

**Comment by mgarabed** [comment]
That's very strange.  I've tried a few different ways locally and can't replicate.

Is there anything special about how the AR11 is deployed?  Maybe virtual on a different port or behind a firewall?  

You can try adding options for extra debug, `--loglevel=debug --logfile=-` which should print out more details in console, but I'm not sure that will tell anything helpful.

**Comment by marwanabdelhadi** [comment]
Thanks Mike, I will try to figure out what is the issue in the connection with the appliance.
